{
 "title": "tado° (Celsius)",
 "description": "Grafana Dashboard for Prometheus eko/tado-exporter that shows the temperature setting, current temperature, humidity and activity for all rooms. A detailed view is shown based on the selected room.",
 "tags": [
  "Prometheus",
  "tado-exporter",
  "Celsius"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "zone",
    "label": "Zones",
    "query": "tado_activity_heating_power_percentage"
   },
   { "name": "temperatureScale", "label": "Temperature Scale", "query": "tado_setting_temperature_value" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<img style=\"display: block; margin-left: auto; margin-right: auto; width: 100px;\" src=\"https://raw.githubusercontent.com/disisto/grafana-dashboard-for-prometheus-tado-exporter/main/img/tado_logo.png\">\n"
   }
  },
  {
   "title": "Temperature: $zone",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Current Temperature"
    },
    {
     "expr": "tado_setting_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Set Temperature"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "options": {
    "content": "<span style=\"font-size:34px\">Temperature</span>\n\n         "
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}"
    }
   ]
  },
  {
   "title": "Heating Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage{zone=\"$zone\"}",
     "legendFormat": "Heating Power"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "options": {
    "content": "<span style=\"font-size:34px\">Humidity</span>         \n"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Max:"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Max:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Avg:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Avg:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "title": "Set Temperature",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_setting_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Set Temperature"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"celsius\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Max:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Avg:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "title": "Heating Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage"
    }
   ]
  },
  {
   "title": "Set Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_setting_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Set Temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Min:"
    }
   ]
  }
 ]
}